In [3]:
# datetime module
print("Loading libraries")
from datetime import date
from datetime import datetime
print('a)', date.today())
print('b)', date.today().strftime("%Y-%m-%d"))
print('c)', date.today().strftime("%B %d %Y"))
print('d)',datetime.now())
print('e)',datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f"))

Loading libraries
a) 2022-02-22
b) 2022-02-22
c) February 22 2022
d) 2022-02-22 17:25:53.509767
e) 2022-02-22 17:25:53.509767


In [11]:
list1 = [i for i in range(10)]
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import py7zr
from pathlib import Path
data_folder = Path("Z:/MarketData/B3/MarketData/Bovespa-Vista/")
file_to_open = data_folder / "NEG_20200310.7z"
dest_folder = Path("C:/Users/aaraujo/OneDrive/Documents/R/b3-bitbucket/bvsp/_rawData/B3/")


In [ ]:
archive = py7zr.SevenZipFile(file_to_open, mode='r')
archive.extractall(dest_folder)
archive.close()

In [13]:
from time import process_time
t1 = process_time()
for i in range(10):
    print(i)
t2 = process_time()
print("Elapsed time:", t2-t1)


0
1
2
3
4
5
6
7
8
9
Elapsed time: 0.0


In [16]:
import numpy as np
np.array([range(5)])

array([[0, 1, 2, 3, 4]])

In [17]:
dir(np.array([range(5)]))


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [18]:
np.arange(0, 5.25, .25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
np.array([True, False, True])

array([ True, False,  True])

In [24]:
np.linspace(0, 2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [25]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
dados = {'Ano': [2014, 2015, 2016, 2017, 2018, 2019],
         'Pais': ['USA', 'China', 'Brazil', 'Canada', 'Portugal', 'Spain'],
         'Sales': [200, 188, 40, 70, 10, 18]}


In [28]:
import pandas as pd
df = pd.DataFrame(dados)
df

Ano      Pais  Sales
0  2014       USA    200
1  2015     China    188
2  2016    Brazil     40
3  2017    Canada     70
4  2018  Portugal     10
5  2019     Spain     18

In [29]:
df['Pais']

0         USA
1       China
2      Brazil
3      Canada
4    Portugal
5       Spain
Name: Pais, dtype: object